### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by koppor** [dspinellis/ai-cli-lib#6]
I try to follow `README.md` and have following config file

```toml
[general]
ai=openai
[openai]
key=sk-N6H...
model=gpt-4
```

The error message is

    /home/koppor/.aicliconfig(2): Initialization file error.

It could be more verbose

**Comment by koppor** [comment]
Maybe, the output of the error could follow the [errorformat](https://github.com/reviewdog/reviewdog#errorformat) format. Currently, I don't know, what `(2)` means.

**Comment by koppor** [comment]
OK, it is always the first key/value pair in the general section:

```toml
[general]
something = value
```
